/*
 *  This Java source file was generated by the Gradle 'init' task.
 */

package com.squadstack.traffic;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public void printHello() {
    System.out.println("Hello");
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
